%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 385.3611656134701
Camera1.fy: 386.27203140371165
Camera1.cx: 321.3031130046934
Camera1.cy: 234.31929677859483

# Pinhole distortion parameters
Camera.k1: 0.003293802203676787
Camera.k2: -0.0008986445461451523
Camera.p1: 0.00000981141488955127
Camera.p2: 0.0000007814611767280166

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 385.16363484248285
Camera2.fy: 386.13479457434124
Camera2.cx: 320.32213563911364
Camera2.cy: 234.3437420781108

# Pinhole distortion parameters
Camera.k1: 0.01839345204765405
Camera.k2: -0.002663469387161469
Camera.p1: 0.000017624116097132693
Camera.p2: -0.0003293386821552823

# Kalibr only gives transform from left camera to right camera,
# We need to invert that to get this:
# Transformation matrix from right camera to left camera

# Same as cam1: T_cn_cnm1
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [0.9999943499537441, 0.0003104788274457673, -0.003347187398289457, -0.0501160864293067,
         -0.0003109838307374656, 0.9999999403412829, -0.00015035451606191228, -3.180718885913244e-05,
         0.0033471405167067154, 0.00015139458771125852, 0.9999943868492629, -0.00047510728369423315,
         0.0, 0.0, 0.0, 1.0]

# Overlapping area between images (to be updated)
#Camera1.overlappingBegin: 0
#Camera1.overlappingEnd: 848

#Camera2.overlappingBegin: 0
#Camera2.overlappingEnd: 848

# Camera resolution
Camera.width: 640
Camera.height: 480

# Camera frames per second
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 50.0

#--------------------------------------------------------------------------------------------
# IMU Parameters
#--------------------------------------------------------------------------------------------

# Inverse of cam0: T_cam_imu
# Transformation from body-frame (imu) to left camera
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [0.99997929, 0.00629932, -0.00131711, -0.00509456,
          -0.00630936, 0.99995000, -0.00775862, 0.00528122,
          0.00126817, 0.00776677, 0.99996903, 0.02643614,
          0.00000000, 0.00000000, 0.00000000, 1.00000000]

# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 0

# IMU noise
# Should I be passing in the regular noise density or discrete noise density???
IMU.NoiseGyro: 0.002049600985797649 # rad/s^0.5
IMU.NoiseAcc: 0.02064189891192468 # m/s^1.5
IMU.GyroWalk: 0.00003199855545594742 # rad/s^1.5
IMU.AccWalk: 0.0022919238444020808 # m/s^2.5
IMU.Frequency: 200.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1500 # Tested with 1250
#ORBextractor.nFeatures: 2000 # Tested with 1250

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 15
ORBextractor.minThFAST: 3

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 2.0
